### ISSUE TITLE
xlsxはね．

### ISSUE THREAD

**Issue by daddygongon** [babygongon/-#1]
確かにexcelの入力は面倒ですよね．GUIなんで．
この程度のものなら，CSVとかにしてGUIで対応できますが，
さらに複雑な前処理とか，複数処理とかを見越して，基本操作をメモっておくことは大事ですね．

ただ，データを手で入れるのは危険ですよね．
何らかのファイルフォーマットから吸い上げるような工夫が必要と思います．
Rubyの標準ライブラリにもcsvやYAMLなんかの読み書きが便利なのがあります．
その辺り追加して，使い込んでください．

**Comment by babygongon** [comment]
西谷先生

黄です。

ご指導ありがとうございます。

先生から教えていただいたライブラリを使いこなせるように勉強します。

どうぞよろしくお願いします。


Shigeto R. Nishitani ***@***.***>于2024年1月18日 周四10:27写道：
